"""Python port of ODR-BINDy (Fung et al., arXiv:2507.23426).

Reference implementation: MATLAB package https://github.com/llfung/ODR-BINDy
(MIT licence, (c) 2025 Lloyd Fung). Files ported, with their Python names:

  DerivativeUtils/FD.m                  -> fd_matrices           (interior stencils only)
  lib_func/Polynomial{D}D{O}O[d|dd].m   -> PolynomialLibrary     (generic, same term order)
  ODR-DynSys/EnsembleLinRegress_Wprior  -> ensemble_lin_regress_wprior
  ODR-DynSys/Jsq_xp.m                   -> jsq_xp
  ODR-DynSys/d2Jdp2_GaussNewtonEst.m    -> d2jdp2_gauss_newton_est
  ODR-DynSys/ODR_BINDy_Regression.m     -> odr_bindy_regression
  FullGreedy/ODR_BINDy_Greedy.m         -> odr_bindy_greedy (incl. RemovalDecision)

Structure and defaults are those of the MATLAB code: MaxNoiseIter=2,
StepTolerance=1e-12, LinUseDenoise=True, MinInitialTrial=4,
MaxInitialTrial=16, MaxFailedRun=2, ContRunStop=2, IniGuessUsePrev=True,
UseGaussNewtonEst=True; lsqnonlin FunctionTolerance=5e-8, MaxIterations
100 (candidate fits) / 1000 doubling on each initial trial; ensemble
initial guess 100 / 1000 bootstrap samples with bragging (median); the
Lorenz.m hyper-parameters SigmaY=1e-4, SigmaP=1e2, 6th-order FD.

Differences from MATLAB (and why)
---------------------------------
1. Optimiser: MATLAB ``lsqnonlin`` ('trust-region-reflective', no bounds,
   default PrecondBandWidth=Inf i.e. direct factorisation of the GN system)
   is replaced by ``_lsqnonlin``: Gauss-Newton steps from an exact structured
   solve of J'J s = -J'r (banded Cholesky of the x-block after point-major
   reordering + Schur complement for p, Jacobi-scaled), globalised by
   Armijo step-halving. Why: the problem is extremely stiff (residuals scaled
   by 1/SigmaY = 1e4 vs 1/SigmaX ~ 0.4; cond(J'J) ~ 1e16). Tried and rejected
   on the Lorenz full-library fit: scipy least_squares(trf, lsmr) did not
   converge in 1000 evaluations (92 s); a hand-written unscaled/scaled 2-D
   subspace trust region (MATLAB's TRF step) and MATLAB-rule Levenberg-
   Marquardt both stalled at resnorm 1.7e3-2.6e6 after 300-1000 iterations,
   while the GN line search reaches resnorm 1445.5 in 25 iterations (4 s).
   Stop tests: |df| <= FunctionTolerance(5e-8)*(1+f), |step| <=
   StepTolerance*(1+|x|), |grad|_inf < 1e-6; MaxIterations 100 / 1000 as in
   MATLAB. Exit flags: >0 converged, 0 = MaxIterations, -99 = exception.
2. Only the default Hessian path (UseGaussNewtonEst=True, d2Jdp2_GaussNewtonEst)
   is ported. The full d2Jdp2.m / dJdx.m / Jsq_x.m path is used only when
   UseGaussNewtonEst=False, which neither the greedy default nor Lorenz.m uses.
   Requesting it raises NotImplementedError instead of silently substituting.
3. Random numbers: MATLAB ``bootstrp``/``randn`` streams cannot be reproduced;
   numpy ``Generator`` streams are used (seedable via ``seed``). Hence the
   noisy Lorenz data are statistically, not bitwise, identical to rng(12).
4. FD.m: only the interior (FullMatFlag=false) branch, as used by Lorenz.m.
   Stencils are generated by the same Vandermonde solve as CentralFD (exactly
   equal to the hard-coded 2/4/6/8/10 rows).
5. Library: one generic polynomial generator replaces the per-dimension
   hand-written files; term order (1, x, y, z, x^2, xy, xz, y^2, yz, z^2, ...)
   matches Polynomial3D2O / Polynomial3D3O. Third derivatives are not needed
   on the Gauss-Newton path and are not provided.
6. Plotting, SaveProgress/LoadProgressFile are dropped (I/O only).
7. The ``chol`` fallback ``logdet`` (MATLAB File-Exchange helper) is replaced
   by ``numpy.linalg.slogdet``.

Layout convention (identical to MATLAB): parameter mask is a flat
column-major (Fortran) boolean vector of length M*ND; x vectors are the
Fortran-flattened (Nx, ND) state; p is ordered equation-by-equation.
"""
from __future__ import annotations

import itertools
import time
from dataclasses import dataclass, field

import numpy as np
import scipy.linalg
import scipy.sparse as sp
import scipy.sparse.linalg as spla


__all__ = [
    "PolynomialLibrary", "fd_matrices", "ensemble_lin_regress_wprior",
    "jsq_xp", "d2jdp2_gauss_newton_est", "odr_bindy_regression",
    "odr_bindy_greedy", "fit",
]


# ---------------------------------------------------------------- library
class PolynomialLibrary:
    """Polynomial dictionary with analytic first/second derivatives in x."""

    def __init__(self, n_dim: int, order: int, names=None):
        self.D = n_dim
        self.order = order
        self.exps = []
        for k in range(order + 1):
            for comb in itertools.combinations_with_replacement(range(n_dim), k):
                e = np.zeros(n_dim, dtype=int)
                for c in comb:
                    e[c] += 1
                self.exps.append(e)
        self.exps = np.array(self.exps)
        self.M = len(self.exps)
        names = names or [f"x{i}" for i in range(n_dim)]
        self.names = []
        for e in self.exps:
            s = "*".join(f"{names[i]}^{e[i]}" if e[i] > 1 else names[i]
                         for i in range(n_dim) if e[i] > 0)
            self.names.append(s or "1")

    @staticmethod
    def _mono(X, e):
        out = np.ones(X.shape[0])
        for i, k in enumerate(e):
            if k > 0:
                out = out * X[:, i] ** k
        return out

    def theta(self, X):
        return np.stack([self._mono(X, e) for e in self.exps], axis=1)

    def dtheta(self, X):  # (N, M, D)
        N = X.shape[0]
        out = np.zeros((N, self.M, self.D))
        for m, e in enumerate(self.exps):
            for a in range(self.D):
                if e[a] > 0:
                    e2 = e.copy(); e2[a] -= 1
                    out[:, m, a] = e[a] * self._mono(X, e2)
        return out

    def ddtheta(self, X):  # (N, M, D, D)
        N = X.shape[0]
        out = np.zeros((N, self.M, self.D, self.D))
        for m, e in enumerate(self.exps):
            for a in range(self.D):
                if e[a] == 0:
                    continue
                e2 = e.copy(); c1 = e2[a]; e2[a] -= 1
                for b in range(self.D):
                    if e2[b] > 0:
                        e3 = e2.copy(); c2 = e3[b]; e3[b] -= 1
                        out[:, m, a, b] = c1 * c2 * self._mono(X, e3)
        return out


# ---------------------------------------------------------------- FD.m
def fd_matrices(n_pt: int, n_dom: int, dt: float):
    """Interior central-difference matrices (FD.m, FullMatFlag=false)."""
    if n_dom <= 1 or n_dom % 2:
        raise ValueError("N_dom must be a positive even integer")
    k = np.arange(-n_dom // 2, n_dom // 2 + 1, dtype=float)
    MAT = k[None, :] ** np.arange(n_dom + 1)[:, None]
    c1 = np.linalg.solve(MAT, np.eye(n_dom + 1)[:, 1])
    c1[np.abs(c1) < 1e4 * np.finfo(float).eps] = 0.0
    c0 = np.zeros(n_dom + 1); c0[n_dom // 2] = 1.0
    n_eq = n_pt - n_dom
    I = sp.diags(list(c0), list(range(n_dom + 1)), shape=(n_eq, n_pt), format="csr")
    D1 = sp.diags(list(c1 / dt), list(range(n_dom + 1)), shape=(n_eq, n_pt), format="csr")
    I.eliminate_zeros()
    return I, D1


# ---------------------------------------------------------------- data
@dataclass
class ODRData:
    Xdata: np.ndarray        # (Nx, ND)
    lib: PolynomialLibrary
    IMat: sp.csr_matrix      # (Neq, Nx)
    DMat: sp.csr_matrix
    SigmaX: np.ndarray       # (Nx, ND)
    SigmaY: np.ndarray       # (Neq, ND)
    SigmaBeta: np.ndarray    # (M, ND)
    Nx: int = field(init=False)
    ND: int = field(init=False)
    Neq: int = field(init=False)
    M: int = field(init=False)

    def __post_init__(self):
        self.Nx, self.ND = self.Xdata.shape
        self.Neq = self.IMat.shape[0]
        self.M = self.lib.M
        self.kI = sp.kron(sp.eye(self.ND), self.IMat, format="csr")
        self.kD = sp.kron(sp.eye(self.ND), self.DMat, format="csr")

    def sb_masked(self, mask):
        return self.SigmaBeta.ravel(order="F")[mask]


def _unflat(v, n, nd):
    return v.reshape((n, nd), order="F")


def _mask2d(mask, M, ND):
    return mask.reshape((M, ND), order="F")


def _df_diag(df, Nx, ND):
    """Block matrix with block (d, b) = diag(df[:, d, b])."""
    blocks = [[sp.diags(df[:, d, b]) for b in range(ND)] for d in range(ND)]
    return sp.bmat(blocks, format="csr")


# ---------------------------------------------------------------- Jsq_xp.m
def jsq_xp(Xp, data: ODRData, mask, jac=False):
    Nx, ND, Neq, M = data.Nx, data.ND, data.Neq, data.M
    m2 = _mask2d(mask, M, ND)
    x = _unflat(Xp[:Nx * ND], Nx, ND)
    p = Xp[Nx * ND:]
    Np = p.size
    Theta = data.IMat @ data.lib.theta(x)
    dx = data.DMat @ x
    delta = (x - data.Xdata) / data.SigmaX
    eta = np.empty((Neq, ND))
    start = 0
    if jac:
        dD = data.lib.dtheta(x)
        df = np.empty((Nx, ND, ND))
        detadp = np.zeros((Neq * ND, Np))
    for d in range(ND):
        nd = int(m2[:, d].sum())
        pl = p[start:start + nd]
        eta[:, d] = (dx[:, d] - Theta[:, m2[:, d]] @ pl) / data.SigmaY[:, d]
        if jac:
            df[:, d, :] = np.einsum("nma,m->na", dD[:, m2[:, d], :], pl)
            detadp[d * Neq:(d + 1) * Neq, start:start + nd] = \
                -Theta[:, m2[:, d]] / data.SigmaY[:, d][:, None]
        start += nd
    sb = data.sb_masked(mask)
    out = np.concatenate([eta.ravel(order="F"), delta.ravel(order="F"), p / sb])
    if not jac:
        return out
    detadx = sp.diags(1.0 / data.SigmaY.ravel(order="F")) @ \
        (data.kD - data.kI @ _df_diag(df, Nx, ND))
    J = sp.bmat([
        [detadx, sp.csr_matrix(detadp)],
        [sp.diags(1.0 / data.SigmaX.ravel(order="F")), None],
        [None, sp.diags(1.0 / sb)],
    ], format="csr")
    return out, J


# ------------------------------------------------ d2Jdp2_GaussNewtonEst.m
def d2jdp2_gauss_newton_est(x, p, data: ODRData, mask):
    Nx, ND, Neq, M = data.Nx, data.ND, data.Neq, data.M
    m2 = _mask2d(mask, M, ND)
    Np = p.size
    lib = data.lib
    Dm, dD, ddD = lib.theta(x), lib.dtheta(x), lib.ddtheta(x)
    f = np.empty((Nx, ND)); df = np.empty((Nx, ND, ND)); ddf = np.empty((Nx, ND, ND, ND))
    pd_ind = []
    start = 0
    for d in range(ND):
        nd = int(m2[:, d].sum())
        ps = np.arange(start, start + nd); pd_ind.append(ps)
        pl = p[ps]
        f[:, d] = Dm[:, m2[:, d]] @ pl
        df[:, d, :] = np.einsum("nma,m->na", dD[:, m2[:, d], :], pl)
        ddf[:, d, :, :] = np.einsum("nmab,m->nab", ddD[:, m2[:, d], :, :], pl)
        start += nd
    eta = data.DMat @ x - data.IMat @ f
    SYv = data.SigmaY.ravel(order="F")
    eta_ib = sp.diags(1.0 / SYv) @ (data.kD - data.kI @ _df_diag(df, Nx, ND))

    eta_im = np.zeros((Nx, ND, Np))
    eta_imb = np.zeros((Nx, ND, Np, ND))
    for d in range(ND):
        eta_im[:, d, pd_ind[d]] = Dm[:, m2[:, d]]
        eta_imb[:, d, pd_ind[d], :] = dD[:, m2[:, d], :]

    g = -(data.IMat.T @ (eta / data.SigmaY ** 2))           # (Nx, ND)
    ee_iab = np.einsum("nc,ncab->nab", g, ddf)              # (Nx, a, b)
    blocks = [[sp.diags(ee_iab[:, a, b]) for b in range(ND)] for a in range(ND)]
    LHS = (eta_ib.T @ eta_ib + sp.bmat(blocks)
           + sp.diags(1.0 / data.SigmaX.ravel(order="F") ** 2)).tocsc()

    ee_ian = np.einsum("nc,ncmb->nbm", g, eta_imb).reshape((Nx * ND, Np), order="F")
    Em = (-(data.IMat @ eta_im.reshape((Nx, ND * Np), order="F"))
          ).reshape((Neq, ND, Np), order="F") / data.SigmaY[:, :, None]
    Em = Em.reshape((Neq * ND, Np), order="F")
    RHS = -ee_ian - eta_ib.T @ Em
    dxdp = spla.splu(LHS).solve(np.asarray(RHS))
    t2 = eta_ib @ dxdp + Em
    SX2 = 1.0 / data.SigmaX.ravel(order="F") ** 2
    return t2.T @ t2 + dxdp.T @ (SX2[:, None] * dxdp) + np.diag(data.sb_masked(mask) ** -2.0)


# ------------------------------------------- EnsembleLinRegress_Wprior.m
def ensemble_lin_regress_wprior(X, data: ODRData, mask, n_samples, rng, bragging=True):
    ND, Neq, M = data.ND, data.Neq, data.M
    m2 = _mask2d(mask, M, ND)
    Th_all = data.IMat @ data.lib.theta(X)
    out = []
    for d in range(ND):
        sbl = data.SigmaBeta[m2[:, d], d]
        Th = Th_all[:, m2[:, d]]
        sy = data.SigmaY[:, d]
        dx = (data.DMat @ X[:, d]) / sy ** 2
        coeff = np.empty((n_samples, Th.shape[1]))
        for ll in range(n_samples):
            ind = rng.integers(0, Neq, Neq)
            T_ = Th[ind]
            coeff[ll] = np.linalg.solve(T_.T @ (T_ / sy[ind, None] ** 2) + np.diag(sbl ** -2.0),
                                        T_.T @ dx[ind])
        out.append(np.median(coeff, 0) if bragging else coeff.mean(0))
    return np.concatenate(out)


# -------------------------------------------- ODR_BINDy_Regression.m
class _GNSolver:
    """Exact solve of (J'J) s = b exploiting structure: the x-block is banded
    after point-major permutation; the few p columns are handled by a Schur
    complement. Numerically equivalent to a sparse direct factorisation."""

    def __init__(self, A, nx, nd):
        n = nx * nd
        self.n = n
        perm = np.arange(n).reshape(nd, nx).T.ravel()
        self.perm, self.iperm = perm, np.argsort(perm)
        A = A.tocsr()
        self.c = 1.0 / np.sqrt(A.diagonal())            # Jacobi column scaling
        A = sp.diags(self.c) @ A @ sp.diags(self.c)
        B = A[:n, :n][perm][:, perm].tocoo()
        up = B.row <= B.col
        bw = int((B.col[up] - B.row[up]).max())
        ab = np.zeros((bw + 1, n))
        ab[bw + B.row[up] - B.col[up], B.col[up]] = B.data[up]
        self.cb = scipy.linalg.cholesky_banded(ab)
        self.Axp = A[:n, n:].toarray()
        App = A[n:, n:].toarray()
        self.S = App - self.Axp.T @ self._sx(self.Axp) if self.Axp.size else App

    def _sx(self, R):
        return scipy.linalg.cho_solve_banded((self.cb, False), R[self.perm])[self.iperm]

    def solve(self, b):
        n = self.n
        b = self.c * b
        if self.Axp.size == 0:
            return self.c * self._sx(b)
        b2 = np.linalg.solve(self.S, b[n:] - self.Axp.T @ self._sx(b[:n]))
        return self.c * np.concatenate([self._sx(b[:n] - self.Axp @ b2), b2])


def _lsqnonlin(fun_jac, x0, max_iter, opts, nx, nd):
    """Gauss-Newton least squares with exact linear solves and a backtracking
    (step-halving) line search on the sum of squares. Returns (x, resnorm,
    exitflag): >0 converged, 0 MaxIterations reached, <0 failure.
    """
    tolf, tolx, tolg = 5e-8, opts["StepTolerance"], 1e-6
    try:
        x = x0.copy()
        r, J = fun_jac(x, True)
        f = r @ r
        for _ in range(max_iter):
            g = J.T @ r
            if np.linalg.norm(g, np.inf) < tolg:
                return x, f, 1
            s = -_GNSolver((J.T @ J).tocsc(), nx, nd).solve(g)
            slope = g @ s                       # = d(f/2)/dt along s, < 0
            t = 1.0
            while True:
                rn = fun_jac(x + t * s, False)
                fn = rn @ rn
                if np.isfinite(fn) and fn / 2 <= f / 2 + 1e-4 * t * slope:
                    break
                t /= 2
                if t < 1e-10:
                    return x, f, 2              # no decrease possible along GN
            x_old, f_old = x, f
            x = x + t * s
            r, J = fun_jac(x, True)
            f = fn
            if abs(f_old - f) <= tolf * (1 + f_old):
                return x, f, 3
            if t * np.linalg.norm(s) <= tolx * (1 + np.linalg.norm(x_old)):
                return x, f, 2
        return x, f, 0
    except Exception:  # MATLAB: try/catch around lsqnonlin
        return None, np.inf, -99


def odr_bindy_regression(data: ODRData, mask, max_iter, n_ens, opts, rng, x_ini=None):
    """Returns (w (M,ND), J_Evi, Xout (Nx,ND), exitflag)."""
    if not opts["UseGaussNewtonEst"]:
        raise NotImplementedError("only the default Gauss-Newton Hessian path is ported")
    Nx, ND, M = data.Nx, data.ND, data.M
    x_ini = (data.Xdata if x_ini is None else x_ini).ravel(order="F")
    jjj, exitflag, H = 0, 1, None
    w = np.zeros((M, ND)); Xout = np.zeros((Nx, ND)); resnorm = np.inf
    while (H is None or np.any(np.linalg.eigvalsh(H) < 0)) and exitflag > 0 \
            and jjj < opts["MaxNoiseIter"]:
        Xlin = _unflat(x_ini, Nx, ND) if opts["LinUseDenoise"] else data.Xdata
        plin = ensemble_lin_regress_wprior(Xlin, data, mask, n_ens, rng)
        Xp, resnorm, exitflag = _lsqnonlin(
            lambda v, j: jsq_xp(v, data, mask, j), np.concatenate([x_ini, plin]),
            max_iter, opts, Nx, ND)
        if Xp is None:
            exitflag = 0; w = np.zeros((M, ND)); Xout = np.zeros((Nx, ND))
        else:
            xt, pt = Xp[:Nx * ND], Xp[Nx * ND:]
            Xout = _unflat(xt, Nx, ND)
            if exitflag > 0:
                H = d2jdp2_gauss_newton_est(Xout, pt, data, mask)
            wf = np.zeros(M * ND); wf[mask] = pt
            w = wf.reshape((M, ND), order="F")
        jjj += 1
    if exitflag <= 0 or jjj >= opts["MaxNoiseIter"]:
        return w, np.inf, Xout, exitflag
    Hs = H / 2 / np.pi
    try:
        ld = np.sum(np.log(np.diag(np.linalg.cholesky(Hs))))
    except np.linalg.LinAlgError:
        ld = np.linalg.slogdet(Hs)[1] / 2
    npar = int(mask.sum())
    J = resnorm / 2 + np.log(2 * np.pi) * npar / 2 + np.sum(np.log(data.sb_masked(mask))) + ld
    return w, J, Xout, exitflag


# --------------------------------------------------- ODR_BINDy_Greedy.m
DEFAULTS = dict(MaxNoiseIter=2, StepTolerance=1e-12, LinUseDenoise=True,
                MinInitialTrial=4, MaxInitialTrial=16, MaxFailedRun=2,
                ContRunStop=2, IniGuessUsePrev=True, UseGaussNewtonEst=True,
                VerboseLevel=0)


def _removal_decision(mask, J_i, m, M, ND):
    if np.all(np.isinf(J_i)):
        return False, mask, -1
    order = np.argsort(J_i, kind="stable")
    for ii in order:
        mn = mask.copy(); mn[m[ii]] = False
        if _mask2d(mn, M, ND).any(0).all():
            break
    if np.isinf(J_i[ii]):
        return False, mask, -1
    return True, mn, ii


def odr_bindy_greedy(Xdata, lib, IMat, DMat, SigmaX, SigmaY, SigmaP, options=None, seed=0):
    """Returns (Xi (M,ND), J_Evi_out, X_denoised, history)."""
    opts = dict(DEFAULTS); opts.update(options or {})
    rng = np.random.default_rng(seed)
    data = ODRData(np.asarray(Xdata, float), lib, IMat, DMat, SigmaX, SigmaY, SigmaP)
    Nx, ND, M = data.Nx, data.ND, data.M
    NpAll = M * ND
    mask = np.ones(NpAll, bool)
    it1, it2 = 100, 1000        # lsqnonlinopt / lsqnonlinopt2 MaxIterations
    ens1, ens2 = 100, 1000
    say = (lambda *a: print(*a, flush=True)) if opts["VerboseLevel"] >= 1 else (lambda *a: None)

    w_j, X_j, J_j = [None] * (NpAll - ND), [None] * (NpAll - ND), np.full(NpAll - ND, np.inf)
    J, calls, exitflag_loc = np.inf, 0, -1
    w = Xout_ini = w_ = Xout_ini_ = None
    while (calls < opts["MinInitialTrial"] or exitflag_loc <= 0 or J == np.inf) \
            and calls < opts["MaxInitialTrial"]:
        w_, J_, Xout_ini_, exitflag_loc = odr_bindy_regression(data, mask, it2, ens2, opts, rng)
        calls += 1
        it2 *= 2
        if J_ < J and exitflag_loc > 0:
            J, w, Xout_ini = J_, w_, Xout_ini_
        say(f"initial trial {calls}: J={J_:.3f} exit={exitflag_loc}")
    if calls >= opts["MaxInitialTrial"]:
        return w_, np.inf, Xout_ini_, dict(failed=True)

    j, cont, failed = 1, 0, 0
    while j <= NpAll - ND and cont < opts["ContRunStop"] and failed < opts["MaxFailedRun"]:
        m = np.flatnonzero(mask)
        J_i = np.full(m.size, np.inf)
        X_i = np.zeros((m.size, Nx, ND)); w_i = np.zeros((m.size, M, ND))
        for ii, i in enumerate(m):
            ml = mask.copy(); ml[i] = False
            if _mask2d(ml, M, ND).any(0).all():
                w_i[ii], J_i[ii], X_i[ii], _ = odr_bindy_regression(
                    data, ml, it1, ens1, opts, rng, Xout_ini)
        decided = False
        while not decided:
            proceed, mask_, i_min = _removal_decision(mask, J_i, m, M, ND)
            if opts["IniGuessUsePrev"] and proceed:
                w_ini_, J_ini_, Xout_ini_, exitflag_loc = odr_bindy_regression(
                    data, mask_, it2, ens2, opts, rng, X_i[i_min])
            else:
                exitflag_loc, J_ini_ = -1, np.inf
            while (exitflag_loc <= 0 or J_ini_ == np.inf) and failed < opts["MaxFailedRun"]:
                w_ini_, J_ini_, Xout_ini_, exitflag_loc = odr_bindy_regression(
                    data, mask_, it2, ens2, opts, rng)
                failed += 1
            if proceed and failed >= opts["MaxFailedRun"]:
                J_i[i_min] = np.inf; failed = 0
            else:
                decided = True
        if proceed:
            k = j - 1
            if J_ini_ < J_i[i_min]:
                X_j[k], w_j[k], J_j[k] = Xout_ini_, w_ini_, J_ini_
            else:
                X_j[k], w_j[k], J_j[k] = X_i[i_min], w_i[i_min], J_i[i_min]
            Xout_ini = X_j[k]
            say(f"removal {j}: dropped flat index {m[i_min]}, J={J_j[k]:.3f}")
            if j > 2:
                cont = cont + 1 if J_j[k] >= J_j[k - 1] else 0
            mask = mask_
            j += 1
        else:
            Xout_ini = Xout_ini_
    k = int(np.argmin(J_j))
    return w_j[k], J_j[k], X_j[k], dict(J_history=J_j[:j - 1].tolist(), failed=False)


# ------------------------------------------------------------ project API
def fit(F_cols: dict, dt: float, sigma_x, poly_order: int = 2, fd_order: int = 6,
        sigma_y: float = 1e-4, sigma_p: float = 1e2, options=None, seed: int = 0):
    """Fit ODR-BINDy to equally spaced state columns.

    F_cols: {state name: 1-D array (Nx,)}; sigma_x: scalar or dict of noise STDs.
    Returns dict(Xi {state: {term: coef}}, coef (M,ND), terms, states,
    X_denoised {state: array}, J_evidence, runtime_s).
    """
    names = list(F_cols)
    X = np.column_stack([np.asarray(F_cols[k], float) for k in names])
    Nx, ND = X.shape
    lib = PolynomialLibrary(ND, poly_order, names)
    IMat, DMat = fd_matrices(Nx, fd_order, dt)
    sx = np.array([sigma_x[k] for k in names]) if isinstance(sigma_x, dict) \
        else np.full(ND, float(sigma_x))
    t0 = time.perf_counter()
    Xi, J, Xd, hist = odr_bindy_greedy(
        X, lib, IMat, DMat, np.tile(sx, (Nx, 1)), sigma_y * np.ones((IMat.shape[0], ND)),
        sigma_p * np.ones((lib.M, ND)), options, seed)
    return dict(
        Xi={s: {t: float(Xi[m, d]) for m, t in enumerate(lib.names) if Xi[m, d] != 0}
            for d, s in enumerate(names)},
        coef=Xi, terms=lib.names, states=names,
        X_denoised={s: Xd[:, d] for d, s in enumerate(names)},
        J_evidence=float(J), history=hist, runtime_s=time.perf_counter() - t0)
