"""Fetch every emitted reference's author list from its registry and record it.

Rule 11 (NEVER EXPAND AN INITIAL) needs a record of what was FETCHED. This script is
that record's only writer: for each entry in references.REFS it queries Crossref
(by DOI) or the arXiv API (by eprint) and writes the returned author strings, verbatim,
to paper/author_provenance.md with the fetch date. references.py's given-name gate
reads the file; a name not in it (or in CITATIONS.md) refuses the build.

    python paper/fetch_author_provenance.py             # fetch only what is missing
    python paper/fetch_author_provenance.py --refresh   # re-fetch everything
"""
import datetime, json, os, re, sys, time, urllib.request
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from references import REFS, ROOT  # noqa: E402

OUT = os.path.join(ROOT, "paper", "author_provenance.md")
UA = {"User-Agent": "mof-ladder-citation-gate (mailto:abdulbatayhi@gmail.com)", "Accept": "*/*"}


def get(url):
    # arXiv's API intermittently answers Python's client with HTTP 406 while
    # answering curl, so try curl first and fall back to urllib.
    import subprocess
    r = subprocess.run(["curl", "-sf", "-A", UA["User-Agent"], url], capture_output=True)
    if r.returncode == 0 and r.stdout:
        return r.stdout
    for attempt in range(6):
        try:
            return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40).read()
        except Exception as e:  # noqa: BLE001
            err = e
            time.sleep(10 * (attempt + 1))
    raise err


def crossref(doi):
    m = json.loads(get("https://api.crossref.org/works/" + doi))["message"]
    return [f"{a.get('given', '')} {a.get('family', a.get('name', ''))}".strip()
            for a in m.get("author", [])], (m.get("title") or [""])[0]


def arxiv(eprint):
    x = ET.fromstring(get("https://export.arxiv.org/api/query?id_list=" + eprint))
    ns = {"a": "http://www.w3.org/2005/Atom"}
    e = x.find("a:entry", ns)
    return [n.text.strip() for n in e.findall("a:author/a:name", ns)], \
        re.sub(r"\s+", " ", e.find("a:title", ns).text.strip())


def previous_rows():
    """Rows already fetched. A rate-limited rerun must not discard earlier successes."""
    if not os.path.exists(OUT):
        return {}
    out = {}
    for line in open(OUT, encoding="utf-8"):
        m = re.match(r"\| (\w+) \| (Crossref|arXiv) ", line)
        if m:
            out[m.group(1)] = line.rstrip()
    return out


def main():
    refresh = "--refresh" in sys.argv
    prev = {} if refresh else previous_rows()
    rows, missing = [], []
    for key, _, _, f, _, _ in REFS:
        if key in prev:
            rows.append(prev[key])
            continue
        try:
            if f.get("doi"):
                src, (auth, title) = "Crossref " + f["doi"], crossref(f["doi"])
            elif f.get("eprint"):
                src, (auth, title) = "arXiv " + f["eprint"], arxiv(f["eprint"])
                time.sleep(20)
            else:
                missing.append(key)
                continue
        except Exception as e:  # noqa: BLE001
            missing.append(f"{key} (fetch failed: {e})")
            continue
        # Crossref can return line breaks INSIDE a title or a given name ("Prediction\nof
        # MOF ...", "Thomas\nD."), which split this markdown row and silently dropped
        # every author after the break from the provenance the gate checks against
        ws = lambda s: " ".join(str(s).split())
        title, auth = ws(title), [ws(a) for a in auth]
        rows.append(f"| {key} | {src} | {title} | {'; '.join(auth) or '(no author list returned)'} |")
        print(key, "ok", len(auth))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("# Author strings as fetched\n\nGENERATED by `paper/fetch_author_provenance.py` on "
                 f"{datetime.date.today().isoformat()}. Do not edit by hand.\nEach row is the "
                 "author list the registry returned, verbatim.\n\n| key | source | title | authors |\n"
                 "|---|---|---|---|\n" + "\n".join(rows) + "\n\n## No registry record fetched\n\n"
                 + "\n".join(f"- {m}" for m in missing) + "\n")
    print(f"wrote {OUT}: {len(rows)} fetched, {len(missing)} without a registry record")


if __name__ == "__main__":
    main()
